[project]
name = "mcp-primer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.50.0",
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
    "openai>=1.76.0",
    "python-dotenv>=1.1.0",
]
